### ISSUE TITLE
Marshal object does not decode properly

### ISSUE THREAD

**Issue by FarzadT** [clayzermk1/node-marshal#1]
The following string throws an exception at parse time:

'\u0004\b{\nI"\u000fsession_id\u0006:\u0006ETI"%621c43c4db9732740e2fafd941635f0a\u0006;\u0000TI"\u0010_csrf_token\u0006;\u0000FI"1REC7hnjqnd0mNgEzS0+dYTEzUY7NIL1WbAjMiiHv5kc=\u0006;\u0000FI"\u0019warden.user.user.key\u0006;\u0000T[\bI"\tUser\u0006;\u0000F[\u0006i\u0002�-I""$2a$10$gEd/xhGMcQTRjtaGzH417e\u0006;\u0000TI"\ranon_key\u0006;\u0000FI"\u001dZmFyemFkQGxhZ29hLmNvbQ==\u0006;\u0000FI"\nflash\u0006;\u0000To:%ActionDispatch::Flash::FlashHash\t:\n@usedo:\bSet\u0006:\n@hash{\u0000:\f@closedF:\r@flashes{\u0006:\u000bnoticeI"\u001cSigned in successfully.\u0006;\u0000T:\t@now0'

Stack trace:
MarshalError: unsupported typecode 189 (index: 176, hex: bd, utf8: �)
Feb  6 15:17:25 scene-composer-app_staging logger:     at Marshal._parse (/app/node_modules/marshal/lib/marshal.js:46:15)
Feb  6 15:17:25 scene-composer-app_staging logger:     at Marshal._parseArray (/app/node_modules/marshal/lib/marshal.js:124:22)
Feb  6 15:17:25 scene-composer-app_staging logger:     at Marshal._parse (/app/node_modules/marshal/lib/marshal.js:37:21)
Feb  6 15:17:25 scene-composer-app_staging logger:     at Marshal._parseHash (/app/node_modules/marshal/lib/marshal.js:161:22)
Feb  6 15:17:25 scene-composer-app_staging logger:     at Marshal._parse (/app/node_modules/marshal/lib/marshal.js:41:21)
Feb  6 15:17:25 scene-composer-app_staging logger:     at Marshal.load (/app/node_modules/marshal/lib/marshal.js:254:26)
Feb  6 15:17:25 scene-composer-app_staging logger:     at new Marshal (/app/node_modules/marshal/lib/marshal.js:9:33)

**Comment by clayzermk1** [comment]
Would it be possible for you to provide me with a dump of that object from ruby? i.e. `Marshal.dump(<object>)`

How are you passing `node-marshal` the Marshaled string? Is it precisely the one you provided above?
Which character encoding is that string in? UTF-16?

**Comment by clayzermk1** [comment]
Can you also give me the lines of your JavaScript code where you are instantiating/calling `node-marshal`?

**Comment by clayzermk1** [comment]
I appreciate the report but it's been a few months without any reply. If you can provide me with some dump data to compare, I'll reopen the issue.

**Comment by josuelima** [comment]
Hi,

I'm having a similar problem:

```
MarshalError: unsupported typecode 108 (index: 158, hex: 6c, utf8: l)
```

This is an example of what I'm trying to decode:
```
"\x04\b{\rI\"\x19warden.user.user.key\x06:\x06ET[\a[\x06I\"\x1d554b7aae873deae0a0525cfb\x06;\x00TI\"\"$2a$10$zUBLU9StWQzYayb3VR2Uhe\x06;\x00TI\"\x1dwarden.user.user.session\x06;\x00T{\x06I\"\x14last_request_at\x06;\x00Tl+\a\xadA\xceVI\"\x0fuser_email\x06;\x00FI\"\x1fjosuedsi@gmail.com\x06;\x00TI\"\x10_csrf_token\x06;\x00FI\"1/OVqXmBxyhbkdXexdjqYNr0Q8MbZj/PVL36yGfMKlpY=\x06;\x00FI\"\x14current_team_id\x06;\x00FI\"\x1d554cc9daedc67fdce6000004\x06;\x00TI\"\x13current_locale\x06;\x00F:\aenI\"\x16current_time_zone\x06;\x00FI\"\x10Brazil/East\x06;\x00TI\"\x1cdisplay_welcome_message\x06;\x00FF"
```

Using ruby Marshal it works fine. This is the expected json (given by Marshal.restore):
```
{"warden.user.user.key"=>[["554b7aae873deae0a0525cfb"], "$2a$10$zUBLU9StWQzYayb3VR2Uhe"], "warden.user.user.session"=>{"last_request_at"=>1456357805}, "user_email"=>"josuedsi@gmail.com", "_csrf_token"=>"/OVqXmBxyhbkdXexdjqYNr0Q8MbZj/PVL36yGfMKlpY=", "current_team_id"=>"554cc9daedc67fdce6000004", "current_locale"=>:en, "current_time_zone"=>"Brazil/East", "display_welcome_message"=>false} 
```

Thanks!
