### ISSUE TITLE
Error parsing RubyGems API dependencies endpoint

### ISSUE THREAD

**Issue by simov** [clayzermk1/node-marshal#10]
:wave: this endpoint [/api/v1/dependencies](https://guides.rubygems.org/rubygems-org-api/#misc-methods) states:

> Returns a marshalled array of hashes for all versions of given gems. Each hash contains a gem version with its dependencies making this useful for resolving dependencies.

I'm buffering the response into a Buffer and then I'm passing it to this module as `new Marshal(buf)`

However, it throws an error:

```
MarshalError: unsupported typecode 8 (index: 2, hex: 08, utf8:)
    at Marshal._parse (/node_modules/marshal/lib/marshal.js:54:15)
    at Marshal.load (/node_modules/marshal/lib/marshal.js:345:26)
    at new Marshal (/node_modules/marshal/lib/marshal.js:13:33)
```

I can provide you with a simple snippet that reproduces the issue.

**Comment by clayzermk1** [comment]
`typecode 8` is interesting, I haven't seen that one before.

Using `$ ruby -ropen-uri -rpp -e 'pp Marshal.dump(Marshal.load(open("https://rubygems.org/api/v1/dependencies?gems=rails,thor")))'`, I was able to get a sample dump, but I'm not seeing any instances of `x08` in it. Could you please run that command with the URL you are hitting and upload the contents as a Gist?

**Comment by simov** [comment]
Oh, wow, totally my bad. I was sending `accept-encoding: gzip, deflate` but not decoding it. Works as expected :+1:
