### ISSUE TITLE
Fixnums between -129 and -256 do not parse correctly

### ISSUE THREAD

**Issue by philipcunningham** [clayzermk1/node-marshal#2]
I was using this library as a basis for a similar library in Haskell and noticed along the way that node-marshal doesn't correctly parse values between -129 and -256. I've created a branch with failing test cases here https://github.com/filib/node-marshal/tree/add-failing-test-case.

``` javascript
t.test('-129', function (t) {
  t.equals(m.load(intyNegOneTwoNine).parsed, -129, 'should equal -129');
  t.end();
});
t.test('-256', function (t) {
  t.equals(m.load(intyNegTwoFiveSix).parsed, -256, 'should equal -256');
  t.end();
});
```

[[link](https://github.com/filib/node-marshal/blob/add-failing-test-case/test/marshal.js#L97-L104)]

**Comment by filib** [comment]
``` javascript
      t.test('-129', function (t) {
        t.equals(m.load(intyNegOneTwoNine).parsed, -129, 'should equal -129');
        t.end();
      });
      t.test('-256', function (t) {
        t.equals(m.load(intyNegTwoFiveSix).parsed, -256, 'should equal -256');
        t.end();
      });
```
[[link](https://github.com/filib/node-marshal/blob/add-failing-test-case/test/marshal.js#L97-L104)]

**Comment by philipcunningham** [comment]
This is because 8bit integers have a range of -128 to 127 and you're using readInt8. I can submit a patch later this evening after work.

**Comment by clayzermk1** [comment]
Wow, thank you so much for finding and reporting this! I'd happily merge a PR :smile:

**Comment by clayzermk1** [comment]
Test code looks great :+1:

**Comment by philipcunningham** [comment]
Nice one, I'll prepare a PR in a little bit.

**Comment by clayzermk1** [comment]
I've been looking over it myself for the past bit. I noticed what you meant about `readInt8`. Still investigating, but one byte negative numbers are definitely broken. Cook me up a PR and I'll make sure you get credit.

**Comment by philipcunningham** [comment]
Done!

**Comment by clayzermk1** [comment]
Thanks!

**Comment by clayzermk1** [comment]
I ended up splitting out the tests you made and making them their own commit (e516ba9628f2db275203d1eab2901f8008ea1590). That way I didn't have to falsely attribute work (seemed more "right").

Thanks to your suggestion on the performance I refactored negative three byte integers as well, they should be much faster.

Thank you again for your help and time on this :beers:.

**Comment by philipcunningham** [comment]
:+1: :tada:
