### ISSUE TITLE
Support for bignum ?

### ISSUE THREAD

**Issue by hadan** [clayzermk1/node-marshal#4]
Hi, 
when I want to try deserialize a rails 2.3 session data with some customized key inside the data.
`var sdata = new Buffer(session_data, 'base64');`
`var m = new Marshal(sdata);`

I got
`MarshalError: unsupported typecode 108 (index: 57, hex: 6c, utf8: l)`

After further investigation in ruby 1.8 marshal.c, seems that l is for 'long' (?) which I think it's the equivalent of bignum in ruby. And I know the data inside is integer (Time.now.to_i), I don't why ruby/rails treat it as bignum when serializing it. If you can add support for bignum that would be great.

**Comment by clayzermk1** [comment]
Hi @hadan, could you please give the latest version a go and see if that works for your use case?

**Comment by hadan** [comment]
Hello @clayzermk1. Tried your update, I think the bignum support is ok. Big thank you!
But now marshal stuck with this error:
`MarshalError: unsupported typecode 67 (index: 46, hex: 43, utf8: C)`
which i think it's a custom class/user class in ruby.
My guess is it failed to unpack `ActionController::Flash::FlashHash` class which is not even used in rails 3 session anymore.
I'm not asking you to support for custom class deserializing but if node marshal support this, node marshal maybe the most comprehensive js module to deserialize ruby marshalled data.
Thanks.

**Comment by clayzermk1** [comment]
Supporting Ruby class deserialization is not something I will be implementing. I am open to a PR though if you want to give it a shot. To do it properly, I think it should probably deserialize into a JS "class" that is basically an extended Function prototype. Feel free to open a new issue to continue the discussion there.

I'm glad bignum seems to be working for you at least.
