### ISSUE TITLE
Incorrectly parsing Bignum?

### ISSUE THREAD

**Issue by dvgica** [clayzermk1/node-marshal#5]
Hi there, thanks for this useful library!

It seems that there might be a problem with parsing `Bignum`s, specifically in the context of a hash. For reasons I don't understand, I can't actually make a test where it fails - but I can make it fail just fine in the REPL. Consider the following:

``` ruby
2.2.4 :045 >   Marshal.dump({1=>1499769350, 2=>2}).unpack('H*')
 => ["04087b0769066c2b0706aa645969076907"] 
```

```
> var Marshal = require('marshal')
undefined
> var m = new Marshal
undefined
> m.load(new Buffer("04087b0769066c2b0706aa645969076907", 'hex')).parsed
MarshalError: unsupported typecode 43 (index: 7, hex: 2b, utf8: +)
    at Marshal._parse (/home/dvangeest/projects/test/node_modules/marshal/lib/marshal.js:52:15)
    at Marshal._parseHash (/home/dvangeest/projects/test/node_modules/marshal/lib/marshal.js:170:20)
    at Marshal._parse (/home/dvangeest/projects/test/node_modules/marshal/lib/marshal.js:45:21)
    at Marshal.load (/home/dvangeest/projects/test/node_modules/marshal/lib/marshal.js:264:26)
    at repl:1:3
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
```

I tried unsuccessfully to add a unit test for this case... it passes, which makes me wonder if a) I'm just doing something wrong, or b) if there's a problem with the test framework.

Based on my limited understanding of Ruby's Marshal format, it looks like the index is not being advanced beyond the typecode for `Bignum`. Therefore, the `+` following the `l`, denoting that it's a positive number, is read as the next type code. My JS is not good enough to spot the error, if indeed there is one.

Any ideas?

**Comment by clayzermk1** [comment]
Hi @DWvanGeest, thanks for the report. I created a couple tests and a driver file using your REPL source but was unable to reproduce your issue.

```javascript
var Marshal = require('./index')
var m = new Marshal
var out = m.load(new Buffer("04087b0769066c2b0706aa645969076907", 'hex')).parsed
console.log('out', out)
// out { '1': '1499769350', '2': 2 }
```

Could you please provide the output from:
- `npm ls node-marshal` in your project directory
- `npm ls -g node-marshal` and confirm that the result comes back empty
- `node --version`

**Comment by dvgica** [comment]
Thanks for the quick response. Here's the output:

```
dvangeest@codrus ~/projects/test $ npm ls node-marshal
test@1.0.0 /home/dvangeest/projects/test
└── (empty)

dvangeest@codrus ~/projects/test $ npm ls -g node-marshal
/home/dvangeest/opt/node-v6.9.4-linux-x64/lib
└── (empty)

dvangeest@codrus ~/projects/test $ node --version
v6.9.4
```

**Comment by dvgica** [comment]
Huh, yeah tried your repro case above in the checked-out source, and I get the same result as you.

I will add that I'm pretty new to Node and NPM (and don't really understand the output of the above commands) - it's entirely possible that PEBKAC.

**Comment by dvgica** [comment]
I `rm -rf`'d my `node_modules` dir and tried again. After fresh `npm install` I can reproduce the issue.

Also, since the name of the module is `marshal` and not `node-marshal`....

```
dvangeest@codrus ~/projects/test $ npm ls marshal
test@1.0.0 /home/dvangeest/projects/test
└── marshal@0.2.1 

dvangeest@codrus ~/projects/test $ npm ls -g marshal
/home/dvangeest/opt/node-v6.9.4-linux-x64/lib
└── (empty)
```

I also tried in a completely new project and could still reproduce it.

**Comment by dvgica** [comment]
Ah. Here's a clue. I can reproduce on the `0.2.1` branch but not master. It does appear that the code has been modularized in the branch but not master.

EDIT: The 0.2.1 branch doesn't advance `this._index` like the master code does, so that's probably the issue.

**Comment by clayzermk1** [comment]
> Also, since the name of the module is `marshal` and not `node-marshal`

Gah, sorry, it's been a while.

Regarding 0.2.1 versus master, I see it in `gitk` now. I'll take a look.

**Comment by clayzermk1** [comment]
Phew this is a mess, I don't know what I was thinking. At best, proper bignum support is half implemented. My suggestion at the moment is to use 0.2.0 if it'll work for you. It's gonna take some free time to fix 0.2.1.

**Comment by dvgica** [comment]
Fair enough, we can use 0.2.0. I installed it and verified it works as expected, just to be sure.

**Comment by clayzermk1** [comment]
I know this issue is long in the tooth, but I just refactored the bignum parsing to use `BigInt`.

For people reading this in the future: every version since 0.2.0 - except for 0.2.1 - has supported bignums. This issue should have been closed eons ago. I've updated documentation around 0.2.1 to make it clear that it shouldn't be used.
